# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
[Service]
ExecStart=
ExecStart=/opt/google/cros-containers/bin/garcon --server --no_startup_notify
