#!/bin/sh

# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

UNIT=cros-port-listener.service
STAGE=$1

systemctl --system daemon-reload >/dev/null || true

if [ "${STAGE}" = "remove" ]; then
  deb-systemd-helper mask "${UNIT}" >/dev/null
fi

if [ "${STAGE}" = "purge" ]; then
  deb-systemd-helper purge "${UNIT}" >/dev/null
  deb-systemd-helper unmask "${UNIT}" >/dev/null
fi
